### PR TITLE
fix: add check for variables with the same name

### LINKED ISSUE #665: Bug with existing config.json variable name with upgrade to 2.3.0
## What happened

With the last upgrade to version 2.3.0, the following error occurred:

```
panic: tools flag redefined: tool

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0003bed00, 0xc0003afe00)
	/workspace/vendor/github.com/spf13/pflag/flag.go:848 +0x807
github.com/spf13/pflag.(*FlagSet).VarPF(0xc0003bed00, 0x1cfce80, 0xc0003c4470, 0xc0003c040c, 0x4, 0x0, 0x0, 0xc0003313c0, 0x3e, 0xc0003c4470)
	/workspace/vendor/github.com/spf13/pflag/flag.go:831 +0x10b
github.com/spf13/pflag.(*FlagSet).VarP(...)
	/workspace/vendor/github.com/spf13/pflag/flag.go:837
github.com/spf13/pflag.(*FlagSet).StringVarP(0xc0003bed00, 0xc0003c4470, 0xc0003c040c, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc0003313c0, 0x3e)
	/workspace/vendor/github.com/spf13/pflag/string.go:42 +0xad
github.com/spf13/pflag.(*FlagSet).String(...)
	/workspace/vendor/github.com/spf13/pflag/string.go:60
github.com/ZupIT/ritchie-cli/pkg/cmd.FormulaCommand.addInputFlags(0x2401040, 0x23, 0x23, 0x1cf1340, 0xc000218120, 0x1ce8040, 0xc000203bc0, 0x1ce83a0, 0x2435700, 0xc0003c0340, ...)
	/workspace/pkg/cmd/formula.go:246 +0x4bd
github.com/ZupIT/ritchie-cli/pkg/cmd.FormulaCommand.newFormulaCmd(0x2401040, 0x23, 0x23, 0x1cf1340, 0xc000218120, 0x1ce8040, 0xc000203bc0, 0x1ce83a0, 0x2435700, 0xc000261220, ...)
	/workspace/pkg/cmd/formula.go:161 +0x249
github.com/ZupIT/ritchie-cli/pkg/cmd.FormulaCommand.Add(0x2401040, 0x23, 0x23, 0x1cf1340, 0xc000218120, 0x1ce8040, 0xc000203bc0, 0x1ce83a0, 0x2435700, 0xc000155080, ...)
	/workspace/pkg/cmd/formula.go:115 +0x358
github.com/ZupIT/ritchie-cli/pkg/commands.Build(0xbfe31bb0c21a7b90)
	/workspace/pkg/commands/builder.go:242 +0x5606
main.main()
	/workspace/cmd/main.go:30 +0x56
```

This was due to the fact that I add in my .rit/repos/ folder a repository with a fórmula having a variable name `tool` configured on its config.json file. Some variable names are now 'protected' to avoid problem with local variables.

Removing the related formula from the .rit/repos/ folder resolved the problem, but I wasn't able to use Ritchie CLI at all due to this error.

It would be interesting to warn the user with a friendly message when this occur, to let him know what has to be done to resolve the problem.

### PR DESCRIPTION
**Pull request by lucasdittrichzup**
### Description

A check has been added in case config.json contains inputs with the same name.

In addition, the default help for flags was removed, because when there are inputs with the same name and they have items, the help was incoherent.

<p align="center">
  <a rel="noopener" target="_blank">gif containing the command demonstration</a>
</p>

Fix #665 

### How to verify it

1. Make sure you have a form with inputs with the same name
2. Build the formula
3. Run the formula and verify that Ritchie continues to work

### Changelog

Add check for variables with the same name

### CODE REVIEW

File: pkg/cmd/formula.go [hunk 1]
```diff
@@ -245,14 +245,13 @@ func (f FormulaCommand) addInputFlags(def formula.Definition, flags *pflag.FlagS
...
 
 	for _, in := range config.Inputs {
+		if flags.Lookup(in.Name) != nil {
+			continue
+		}
+
 		switch in.Type {
 		case input.TextType, input.PassType, input.DynamicType:
-			if len(in.Items) > 0 {
-				tutorial := fmt.Sprintf("%s | accepted items for this field [%s]", in.Tutorial, strings.Join(in.Items, ", "))
```
Comment (henriquemoraeszup) [inline pkg/cmd/formula.go:251]: just curious, what was the decision to remove this?

**Review by henriquemoraeszup — COMMENTED** [review]
We might be missing a test for this case

File: pkg/cmd/formula.go (hunk 1 above)
Comment (lucasdittrichzup) [reply pkg/cmd/formula.go:251]: I talked to @kaduartur and decided to take it out, because when we have the case of several inputs with the same name and both have items, it can cause confusion for the user when accessing the help, as shown in the image below:

Imgur

Thus, when applicable, the user must create a generic help on the first input, as in the example:
Imgur
Imgur

**Review by brunasilvazup — APPROVED** [review]
It's excellent solution, congrats :1st_place_medal:

**Review by brunasilvazup — APPROVED** [review]

**Review by henriquemoraeszup — APPROVED** [review]

**Comment by lucasdittrichzup** [comment]
it's working on Linux and Windows
